#define BLACK 0
#define BLUE 1
#define GREEN 2
#define CYAN 3
#define RED 4
#define MAGENTA 5
#define BROWN 6
#define LIGHT_GRAY 7
#define DARK_GRAY 8
#define LIGHT_BLUE 9
#define LIGHT_GREEN A
#define LIGHT_CYAN B
#define LIGHT_RED C
#define LIGHT_MAGENTA D
#define YELLOW E
#define WHITE F