name: Build My OS

on:
  [push, workflow_dispatch]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Install NASM
        run: sudo apt install nasm -y

      - name: Install Zig
        run: wget https://ziglang.org/builds/zig-linux-x86_64-0.14.0.tar.xz && tar -xvf zig-linux-x86_64-0.14.0.tar.xz && sudo mv zig-linux-x86_64-0.14.0/zig /usr/local/bin && sudo mv zig-linux-x86_64-0.14.0/lib /usr/local/lib/zig

      - name: Build Image
        run: make myos.img

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: myos.img
          path: myos.img
